// Auto-generated by deploy script — do not edit manually
export const CONTRACT_ADDRESS = "0x5FbDB2315678afecb367f032d93F642f64180aa3";
export const ADMIN_ADDRESS = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266";
export const NETWORK_CHAIN_ID = 31337;
export const DEPLOYED_AT = "2026-06-14T19:31:30.547Z";
