const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
    console.log("🚀 Starting SecureVoting deployment...\n");

    // Get signers
    const [deployer] = await hre.ethers.getSigners();
    console.log(`📬 Deployer address : ${deployer.address}`);

    const balance = await hre.ethers.provider.getBalance(deployer.address);
    console.log(`💰 Deployer balance : ${hre.ethers.formatEther(balance)} ETH\n`);

    // Deploy contract
    console.log("📦 Deploying SecureVoting contract...");
    const SecureVoting = await hre.ethers.getContractFactory("SecureVoting");
    const voting = await SecureVoting.deploy();
    await voting.waitForDeployment();

    const contractAddress = await voting.getAddress();
    console.log(`✅ SecureVoting deployed to: ${contractAddress}`);
    console.log(`👑 Admin wallet           : ${deployer.address}`);
    console.log(`🔗 Network                : ${hre.network.name}\n`);

    // Seed some example candidates for demo
    if (hre.network.name === "localhost" || hre.network.name === "hardhat") {
        console.log("🌱 Seeding demo candidates...");
        const tx1 = await voting.addCandidate(
            "Alice Johnson",
            "Experienced leader focused on technology innovation and digital transformation for a better future.",
            "https://i.pravatar.cc/300?u=alice"
        );
        await tx1.wait();

        const tx2 = await voting.addCandidate(
            "Bob Williams",
            "Community advocate dedicated to economic growth, sustainability, and equal opportunity for all citizens.",
            "https://i.pravatar.cc/300?u=bob"
        );
        await tx2.wait();

        const tx3 = await voting.addCandidate(
            "Carol Martinez",
            "Healthcare champion with 20 years of experience committed to affordable, accessible public services.",
            "https://i.pravatar.cc/300?u=carol"
        );
        await tx3.wait();

        console.log("✅ 3 demo candidates added.\n");
    }

    // Save deployment info for frontend
    const deploymentInfo = {
        network: hre.network.name,
        chainId: (await hre.ethers.provider.getNetwork()).chainId.toString(),
        contractAddress,
        adminAddress: deployer.address,
        deployedAt: new Date().toISOString(),
        blockNumber: (await hre.ethers.provider.getBlockNumber()),
    };

    const deploymentPath = path.join(__dirname, "../deployment.json");
    fs.writeFileSync(deploymentPath, JSON.stringify(deploymentInfo, null, 2));
    console.log(`📄 Deployment info saved to: ${deploymentPath}`);

    // Also copy ABI to frontend
    const artifactPath = path.join(
        __dirname,
        "../artifacts/contracts/Voting.sol/SecureVoting.json"
    );
    const frontendABIPath = path.join(
        __dirname,
        "../../frontend/src/utils/VotingABI.json"
    );

    if (fs.existsSync(artifactPath)) {
        const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
        fs.writeFileSync(
            frontendABIPath,
            JSON.stringify({ abi: artifact.abi }, null, 2)
        );
        console.log(`📋 ABI copied to frontend: ${frontendABIPath}`);
    }

    // Save contract address to frontend config
    const frontendConfigPath = path.join(
        __dirname,
        "../../frontend/src/utils/contractConfig.js"
    );
    const configContent = `// Auto-generated by deploy script — do not edit manually
export const CONTRACT_ADDRESS = "${contractAddress}";
export const ADMIN_ADDRESS = "${deployer.address}";
export const NETWORK_CHAIN_ID = ${(await hre.ethers.provider.getNetwork()).chainId};
export const DEPLOYED_AT = "${new Date().toISOString()}";
`;
    fs.writeFileSync(frontendConfigPath, configContent);
    console.log(`⚙️  Contract config written to frontend.`);

    console.log("\n🎉 Deployment complete!");
    console.log("═══════════════════════════════════════");
    console.log(`Contract : ${contractAddress}`);
    console.log(`Admin    : ${deployer.address}`);
    console.log(`Network  : ${hre.network.name}`);
    console.log("═══════════════════════════════════════\n");

    if (hre.network.name === "sepolia" || hre.network.name === "goerli") {
        console.log("🔍 Verify on Etherscan:");
        console.log(
            `   npx hardhat verify --network ${hre.network.name} ${contractAddress}`
        );
    }
}

main().catch((error) => {
    console.error("❌ Deployment failed:", error);
    process.exitCode = 1;
});
